services:
  - type: web
    name: mentora-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # or whatever your main file is
    rootDir: backend
    envVars:
      - key: FLASK_ENV
        value: production
